% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={EmployeePromotion},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{EmployeePromotion}
\author{}
\date{\vspace{-2.5em}2023-02-18}

\begin{document}
\maketitle

Este proyecto está realizado por el grupo 3 formado por José Arturo
Espaillat, Johnsiel Castaños, José Delgado, Salama Mohamed-fadel Sidna

El dataset elegido es llamado HR Analytics: Employer Promotion Data
(\url{https://www.kaggle.com/datasets/arashnic/hr-ana?select=test.csv})
sacado de Kaggle, el cual cuenta con 13 columnas y 54808 filas. Estos
datos parten de una empresa la cual tiene un problema debido a que las
promociones definitivas no se anuncian hasta después de evaluar empleado
por empleo haciendo de esto un proceso lento y tedioso. Gracias al
análisis de estos históricos podemos entender cuales son las variables
que más afectan a la promoción para aumentar la eficacia del proceso ya
que ahorran mucho más tiempo al tener claro cuales son los potenciales
candidatos. También los candidatos obtienen un punto de vista de que es
lo que más repercute en su promoción, pudiendo así mejorar cierto
aspecto de cara a la evaluación.

De esta manera conseguimos derribar el muro de las emociones evitando
asi promociones no merecidas a empleados por el mero hecho de caer bien,
conseguiendo así una criticidad para que todos los empleados entiendan
por que son o no promocionados.Esto es un problema a dia de hoy y vemos
muchas publicaciones de como evitar conflictos entre compañeros
\url{https://www.ieie.eu/como-ascender-a-un-empleado-sin-generar-conflictos/}

Personalmente hemos querido abordar este problema porque esto es un
problema real de nuestro dia a dia y nos pareció bastante interesante la
idea de poder analizar este caso. Es cierto que esto es muy relativo a
cada tipo de empresa la cual se fija más en unas variables que en otras
pero nos puede aportar el procedimiento para extrapolarlo a otros campos
Lo que queremos lograr es plantear el análisis de problemas de este
estilo como que visualizacion nos puede ayudar, correlaciones, saber si
nos podemos ahorrar pasos a través de sacar conclusiones
tempranas\ldots{}

En resumen creemos que es bastante interesante el estudio de este
dataset ya que tiene cierta importancia a la hora de poder entender
porque las personas son ascendidas en su trabajo y desde el punto de
vista de la empresa les beneficia en el tiempo ahorrado en estos
procesos de promoción.

Para organizarnos, hemos decidido crear un repositorio en GitHub
(\url{https://github.com/Josdelser/DataScienceEmployeePromotion/tree/develop})
para trabajar simultáneamente. También hemos creado una bolsa de
preguntas y las hemos asignado según las capacidades y aspiraciones de
cada persona. En el caso de que algún miembro quiera obtener una
calificación más alta, deberá realizar un mayor número de preguntas
individuales. Todos los miembros realizarán una pregunta para la parte
grupal y se ha intentado que estas preguntas estén relacionadas con las
preguntas individuales, para poder afrontar mejor el desafío.

A continuación, se detalla la asignación de cada miembro:

Preguntas resueltas:

\begin{verbatim}
¿Nos puede ayudar la visualización a sacar conclusiones temprana?

¿Podemos sacar conclusiones tempranas de que variables afectan prediciendo si será promovido un empleado?

¿Cuáles son los componentes que más explican la variabilidad de nuestro dataset?
\end{verbatim}

Cada miembro realizará la documentación de su parte grupal asignada.
Además en el documento se indicará donde empieza y acaba la parte de
cada miembro para que así sea mas sencilla su evaluación.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Packages}

\CommentTok{\#install.packages("tidyverse")}
\CommentTok{\#install.packages("dplyr")}
\CommentTok{\#install.packages("magrittr")}
\CommentTok{\#install.packages("caret")}
\CommentTok{\#install.packages("plyr")}
\CommentTok{\#install.packages("rattle")}
\CommentTok{\#install.packages("gapminder")}
\CommentTok{\#install.packages("R.devices")}
\CommentTok{\#install.packages("RWeka")}
\CommentTok{\#install.packages("rpart.plot")}
\CommentTok{\#install.packages("RGtk2")}
\CommentTok{\#install.packages("rattle")}
\CommentTok{\#install.packages("factoextra")}
\CommentTok{\#install.packages("gridExtra")}
\CommentTok{\#install.packages("animation")}
\CommentTok{\#install.packages("ggfortify")}


\CommentTok{\# libraries}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rpart)}
\FunctionTok{library}\NormalTok{(rpart.plot)}
\FunctionTok{library}\NormalTok{(rattle)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: tibble
\end{verbatim}

\begin{verbatim}
## Loading required package: bitops
\end{verbatim}

\begin{verbatim}
## Rattle: A free graphical interface for data science with R.
## Versión 5.5.1 Copyright (c) 2006-2021 Togaware Pty Ltd.
## Escriba 'rattle()' para agitar, sacudir y  rotar sus datos.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(RColorBrewer)}
\FunctionTok{library}\NormalTok{(ggfortify)}
\FunctionTok{library}\NormalTok{(vcd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: grid
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{require}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: corrplot
\end{verbatim}

\begin{verbatim}
## corrplot 0.92 loaded
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(magrittr)}
\FunctionTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v forcats 1.0.0     v stringr 1.5.0
## v purrr   1.0.1     v tidyr   1.3.0
## v readr   2.1.4
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x tidyr::extract()   masks magrittr::extract()
## x dplyr::filter()    masks stats::filter()
## x dplyr::lag()       masks stats::lag()
## x purrr::lift()      masks caret::lift()
## x purrr::set_names() masks magrittr::set_names()
## i Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(cluster)}
\FunctionTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gridExtra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'gridExtra'
## 
## The following object is masked from 'package:dplyr':
## 
##     combine
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(stats)}

\FunctionTok{library}\NormalTok{(class)}
\FunctionTok{library}\NormalTok{(plyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ------------------------------------------------------------------------------
## You have loaded plyr after dplyr - this is likely to cause problems.
## If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
## library(plyr); library(dplyr)
## ------------------------------------------------------------------------------
## 
## Attaching package: 'plyr'
## 
## The following object is masked from 'package:purrr':
## 
##     compact
## 
## The following objects are masked from 'package:dplyr':
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#seed}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{28}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Información general del Dataset

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"train.csv"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   employee_id        department    region        education gender
## 1       65438 Sales & Marketing  region_7 Master's & above      f
## 2       65141        Operations region_22       Bachelor's      m
## 3        7513 Sales & Marketing region_19       Bachelor's      m
## 4        2542 Sales & Marketing region_23       Bachelor's      m
## 5       48945        Technology region_26       Bachelor's      m
## 6       58896         Analytics  region_2       Bachelor's      m
##   recruitment_channel no_of_trainings age previous_year_rating
## 1            sourcing               1  35                    5
## 2               other               1  30                    5
## 3            sourcing               1  34                    3
## 4               other               2  39                    1
## 5               other               1  45                    3
## 6            sourcing               2  31                    3
##   length_of_service awards_won. avg_training_score is_promoted
## 1                 8           0                 49           0
## 2                 4           0                 60           0
## 3                 7           0                 50           0
## 4                10           0                 50           0
## 5                 2           0                 73           0
## 6                 7           0                 85           0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "employee_id"          "department"           "region"              
##  [4] "education"            "gender"               "recruitment_channel" 
##  [7] "no_of_trainings"      "age"                  "previous_year_rating"
## [10] "length_of_service"    "awards_won."          "avg_training_score"  
## [13] "is_promoted"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    54808 obs. of  13 variables:
##  $ employee_id         : int  65438 65141 7513 2542 48945 58896 20379 16290 73202 28911 ...
##  $ department          : chr  "Sales & Marketing" "Operations" "Sales & Marketing" "Sales & Marketing" ...
##  $ region              : chr  "region_7" "region_22" "region_19" "region_23" ...
##  $ education           : chr  "Master's & above" "Bachelor's" "Bachelor's" "Bachelor's" ...
##  $ gender              : chr  "f" "m" "m" "m" ...
##  $ recruitment_channel : chr  "sourcing" "other" "sourcing" "other" ...
##  $ no_of_trainings     : int  1 1 1 2 1 2 1 1 1 1 ...
##  $ age                 : int  35 30 34 39 45 31 31 33 28 32 ...
##  $ previous_year_rating: num  5 5 3 1 3 3 3 3 4 5 ...
##  $ length_of_service   : int  8 4 7 10 2 7 5 6 5 5 ...
##  $ awards_won.         : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ avg_training_score  : int  49 60 50 50 73 85 59 63 83 54 ...
##  $ is_promoted         : int  0 0 0 0 0 0 0 0 0 0 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 54808    13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{object.size}\NormalTok{(data)}\SpecialCharTok{/}\DecValTok{1024} \CommentTok{\#KB}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 4073.3 bytes
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{object.size}\NormalTok{(data)}\SpecialCharTok{/}\DecValTok{1024}\SpecialCharTok{\^{}}\DecValTok{2} \CommentTok{\#MB}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 4 bytes
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{object.size}\NormalTok{(data)}\SpecialCharTok{/}\DecValTok{1024}\SpecialCharTok{\^{}}\DecValTok{3} \CommentTok{\#GB}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 0 bytes
\end{verbatim}

Vemos que el número de bytes del dataset es 4073,3 KB o 4,1 MB una vez
lo tenemos cargado

Es verdad que el dataset está presentable pero aún así tenemos que
hacerle una etapa de transformaciones y limpieza. Primero vamos a quitar
todos los NA y duplicados, luego cada mienbro para responder a sus
preguntas hará mas transformaciones.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Número de valores faltantes totales:"}\NormalTok{, }\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Número de valores faltantes totales: 4124"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(data)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

*Aqui empieza la parte de Jose Delgado

Una vez cargado el dataset y tratado mínimamente vamos a pasar a hacer
responder a las preguntas, primero la pregunta grupal:

\begin{verbatim}
¿Podemos sacar conclusiones tempranas de que variables afectan prediciendo si será promovido un empleado?
\end{verbatim}

La cual se plantea responder mediante una predicción utilizando
validación cruzada (cross validation), para ello podemos tirar de
regresión logística o un árbol de decisión. En este caso usaré árboles
de decisión para así también ver qué variables influyen y poder comparar
este resultado con las preguntas individuales

Primero le hacemos preprocesamiento de manera preparatoria a la
predicción, luego dividimos el dataset en conjunto de prueba(test) y
entrenamiento(train) para obtener resultado

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datajose }\OtherTok{\textless{}{-}}\NormalTok{ data}
\end{Highlighting}
\end{Shaded}

Luego convertimos las variables categóricas en factores y definimos
explícitamente los niveles de cada categoría.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dep\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{department)}
\NormalTok{gen\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{gender)}
\NormalTok{recru\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{recruitment\_channel)}
\NormalTok{promo\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{is\_promoted )}
\NormalTok{award\_levels }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{awards\_won)}


\NormalTok{datajose}\SpecialCharTok{$}\NormalTok{department }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{department, }\AttributeTok{levels =}\NormalTok{ dep\_levels)}
\NormalTok{datajose}\SpecialCharTok{$}\NormalTok{gender  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{gender , }\AttributeTok{levels =}\NormalTok{ gen\_levels)}
\NormalTok{datajose}\SpecialCharTok{$}\NormalTok{recruitment\_channel }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{recruitment\_channel, }\AttributeTok{levels =}\NormalTok{ recru\_levels)}
\NormalTok{datajose}\SpecialCharTok{$}\NormalTok{is\_promoted }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{is\_promoted, }\AttributeTok{levels =}\NormalTok{ promo\_levels)}
\NormalTok{datajose}\SpecialCharTok{$}\NormalTok{awards\_won }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datajose}\SpecialCharTok{$}\NormalTok{awards\_won, }\AttributeTok{levels =}\NormalTok{ award\_levels)}
\end{Highlighting}
\end{Shaded}

Partimos de un dataset exclusivo para la predicción y que no afecte a
otros cálculos

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datajosepred }\OtherTok{\textless{}{-}}\NormalTok{datajose}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{division }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(datajosepred}\SpecialCharTok{$}\NormalTok{is\_promoted, }\AttributeTok{p =}\NormalTok{ .}\DecValTok{7}\NormalTok{, }\AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{times =} \DecValTok{1}\NormalTok{)}
\NormalTok{train }\OtherTok{\textless{}{-}}\NormalTok{ datajosepred[division, ]}
\NormalTok{test  }\OtherTok{\textless{}{-}}\NormalTok{ datajosepred[}\SpecialCharTok{{-}}\NormalTok{division, ]}
\end{Highlighting}
\end{Shaded}

Entrenamos el modelo y visualizamos para tener una primera imagen de las
variables decisivas

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(}\AttributeTok{formula =}\NormalTok{  is\_promoted  }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{method =} \StringTok{\textquotesingle{}class\textquotesingle{}}\NormalTok{)}

\FunctionTok{fancyRpartPlot}\NormalTok{(arbol)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-9-1.pdf}

Podemos observar que la variable que más afecta es la puntuación en el
rango superior a 91, donde con un 99\% de posibilidades serás
promocionado. Al tener una variable con tanta importancia se nos viene a
la cabeza otra pregunta: Quitando esta variable, ¿Como sería el árbol
final? Se verá mas adelante.

Pasamos a predecir según clasificación

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prediccion }\OtherTok{\textless{}{-}}\FunctionTok{predict}\NormalTok{(arbol, test, }\AttributeTok{type =} \StringTok{"class"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Ahora toca evaluar el rendimiento según validación cruzada.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valcruz }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}\AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }\AttributeTok{number =} \DecValTok{10}\NormalTok{)}

\NormalTok{arbolfit }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(is\_promoted }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train, }\AttributeTok{method =} \StringTok{"rpart"}\NormalTok{,}
                 \AttributeTok{trControl =}\NormalTok{ valcruz, }\AttributeTok{tuneLength =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Graficamos

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rpart.plot}\NormalTok{(arbolfit}\SpecialCharTok{$}\NormalTok{finalModel, }\AttributeTok{type =} \DecValTok{2}\NormalTok{, }\AttributeTok{extra =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-12-1.pdf}

Mejoramos la visualización para ver mejor el nombre de las variable sy
al estructura del árbol

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prp}\NormalTok{(arbolfit}\SpecialCharTok{$}\NormalTok{finalModel, }\AttributeTok{type =} \DecValTok{2}\NormalTok{, }\AttributeTok{nn =} \ConstantTok{TRUE}\NormalTok{, }
    \AttributeTok{fallen.leaves =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{varlen =} \DecValTok{0}\NormalTok{,  }\AttributeTok{shadow.col =} \StringTok{"gray"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prediccionTest }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbolfit, }\AttributeTok{newdata =}\NormalTok{ test)}
\FunctionTok{confusionMatrix}\NormalTok{(prediccionTest, test}\SpecialCharTok{$}\NormalTok{is\_promoted)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction     0     1
##          0 13861  1044
##          1    45   254
##                                           
##                Accuracy : 0.9284          
##                  95% CI : (0.9242, 0.9324)
##     No Information Rate : 0.9146          
##     P-Value [Acc > NIR] : 2.733e-10       
##                                           
##                   Kappa : 0.2956          
##                                           
##  Mcnemar's Test P-Value : < 2.2e-16       
##                                           
##             Sensitivity : 0.9968          
##             Specificity : 0.1957          
##          Pos Pred Value : 0.9300          
##          Neg Pred Value : 0.8495          
##              Prevalence : 0.9146          
##          Detection Rate : 0.9117          
##    Detection Prevalence : 0.9803          
##       Balanced Accuracy : 0.5962          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

Con estos datos ya podemos sacar conclusiones sobre el modelo:

\begin{itemize}
\item
  Hay 13,861 verdaderos negativos y 254 verdaderos positivos
\item
  Hay 1,044 falsos negativos y 45 falsos positivos
\end{itemize}

Ya con estos valores vemos que el modelo está bien ajustado. Con estos
datos obtenemos una precisión del 92,8\% y una tasa de error del 7,16\%.
También observamos que tenemos mayor capacidad para acertar, es decir
predecir cuándo se va a promover que cuando no se va a promover.

Además observando el arbolfit vemos que ya aparecen más variables que
son relevantes como award\_won y previus\_year\_rating. Añadir que vemos
una fuerte tendencia en el departamento de analiticas, donde superando
los 82 puntos serás promocionado con alta seguridad.

Segunda pregunta

Una vez hecha la predicción, me pregunté si había alguna gráfica que me
hubiese podido ayudar a sacar una conclusión temprana de las variables
que más afectan. Para ello voy a realizar gráficas tanto para variables
numéricas como categóricas.

Pondré el caso de que no hemos predicho todavía y no se qué variables
afectan, de esta manera poder simular un problema real ya que mi
tendencia será ir a por las variables que creo que puedan afectar más.

Volvemos a partir de un dataset exclusivo para esta parte

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datajosegraficas }\OtherTok{\textless{}{-}}\NormalTok{ datajose}
\end{Highlighting}
\end{Shaded}

Primero vamos a ver las variables categóricas. Empezamos por ver si los
estudios influyen, vamos a graficar la distribución de empleados
promovidos según sus estudios

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ education, }\AttributeTok{fill =}\NormalTok{ is\_promoted)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"dodge"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promocionado según estudios"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"Nivel de estudios"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Total"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Promovido"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-16-1.pdf}
Observamos que la mayoría tienen como mínimo el bachillerato y luego el
Master. Podemos pensar que es una variable que afecta debido a las
diferencias entre promovido o no pero no es decisiva o tiene una
importancia mayor.

Repetimos pero con los premios ganados

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ awards\_won, }\AttributeTok{fill =}\NormalTok{ is\_promoted)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promovido por premios ganados"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"Premio"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Total"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Promovido"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-17-1.pdf}
Se observa que en los que están promovidos tiene mayor relevancia tener
un premio, ya que el número de promovidos con premios es notablemente
mayor aunque a simple vista no se observe.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ department, }\AttributeTok{fill =}\NormalTok{ is\_promoted)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promocionado según departamento"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"Departamento"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Total"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Promovido"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-18-1.pdf}
Con este gráfico de barras apiladas vemos que esta variable no afecta
fuertemente a la promoción ya que cada departamento tiene resultados
iguales si no contamos en proporción porque al no saber a qué se dedica
la empresa no podemos justificar el número de empleados por cada
departamento.

Por último vamos a ver si el género afecta.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ gender, }\AttributeTok{fill =}\NormalTok{ is\_promoted)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promovido por géneros"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"Géneros"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Total"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Promovido"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-19-1.pdf}
Aqui vemos que en proporcion que no afecta el género, ya que a simple
vista los porcentajes de promocio segun el sexo parecen cercanoss.

Ahora pasamos a las variables numéricas.

Empezamos con la edad representada en un gráfico de densidad para ver
donde se concentran la mayoría de promocionados por si vemos que la edad
pueda afectar ya que también está relacionada con el tiempo que lleves
en la empresa

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{fill =}\NormalTok{ is\_promoted)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promovido según edad"}\NormalTok{, }
       \AttributeTok{x =} \StringTok{"Edad"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"Promovido"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-20-1.pdf}

El rango es bastante amplio por lo que no vemos que la edad concreta
pueda afectar, pero si puede afectar dependiendo de los años que lleve
en la empresa, es decir, una persona con 40 años tiene más probabilidad
de llevar más tiempo en la empresa que una persona de 20 años. Por eso
vamos a graficar ahora si el tiempo en la empresa afecta

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ is\_promoted, }\AttributeTok{fill =} \FunctionTok{factor}\NormalTok{(previous\_year\_rating))) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Promovido"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Número de empleados"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Gráfico de barras apiladas para la variable \textquotesingle{}previous\_year\_rating\textquotesingle{}"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-21-1.pdf}
Ahora si encontramos dos grupos que afectan a la promoción, los que
llevan 5 años y 3.

Por último vamos a probar con la variable avg\_training\_score para ver
si esta nos afecta.Para ello vamos con un gráfico de cajas y bigotes

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ datajosegraficas, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ is\_promoted, }\AttributeTok{y =}\NormalTok{ avg\_training\_score)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Promovido"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Puntuación de entrenamiento promedio"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Gráfico de cajas y bigotes para la variable \textquotesingle{}avg\_training\_score\textquotesingle{}"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{EmployeePromotionR_files/figure-latex/unnamed-chunk-22-1.pdf}

Observamos que la variable av\_training\_score es bastante importante ya
que por encima de cierto rango se concentra todos los que han sido
promovidos.

La conclusión final que sacamos de estas gráficas está bastante
relacionada con la de la predicción. Vemos que ciertas variables tienden
a afectar de manera directa a la promoción y tanto en gráficas como en
predicción concuerdan unas con otras.

\begin{itemize}
\tightlist
\item
  Aquí empieza la parte grupal de Salama Mohamed-fadel Sidna
\end{itemize}

En esta parte empiezo con la lectura del dataset principal en nueva ds
``data\_Salama'', identificar los diferentes variable y sus tipos ,y el
nombre de variable y observaciones en la dataset principal. Lectura del
dataset data\_Salama.csv

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_Salama }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{ (}\StringTok{"train.csv"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data\_Salama,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   employee_id        department    region        education gender
## 1       65438 Sales & Marketing  region_7 Master's & above      f
## 2       65141        Operations region_22       Bachelor's      m
## 3        7513 Sales & Marketing region_19       Bachelor's      m
## 4        2542 Sales & Marketing region_23       Bachelor's      m
## 5       48945        Technology region_26       Bachelor's      m
##   recruitment_channel no_of_trainings age previous_year_rating
## 1            sourcing               1  35                    5
## 2               other               1  30                    5
## 3            sourcing               1  34                    3
## 4               other               2  39                    1
## 5               other               1  45                    3
##   length_of_service awards_won. avg_training_score is_promoted
## 1                 8           0                 49           0
## 2                 4           0                 60           0
## 3                 7           0                 50           0
## 4                10           0                 50           0
## 5                 2           0                 73           0
\end{verbatim}

Cuáles son los componentes que más explican la variabilidad de nuestro
dataset?

Para responder a esta pregunta seguimos la tecnica de reduccion y luego
aplicamos la tecnica de analisis de los componentes principales PCA.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tuxe9cnica-de-reducciuxf3n-de-la-dimensiuxf3n}{%
\section{Técnica de reducción de la
dimensión}\label{tuxe9cnica-de-reducciuxf3n-de-la-dimensiuxf3n}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Analisis de componentes principales creando un subconjunto de nuestra
base de datos con las variables numéricas, y analizar sus correlaciones.

Empezamos con la matriz de correlaciones de estas variables

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ep\_PC}\OtherTok{=}\NormalTok{data\_Salama[,}\FunctionTok{c}\NormalTok{(}\StringTok{"no\_of\_trainings"}\NormalTok{, }\StringTok{"age"}\NormalTok{, }\StringTok{"previous\_year\_rating"}\NormalTok{, }\StringTok{"length\_of\_service"}\NormalTok{, }\StringTok{"avg\_training\_score"}\NormalTok{)]}
\NormalTok{epc}\OtherTok{=}\FunctionTok{cor}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(ep\_PC))}
\NormalTok{epc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      no_of_trainings          age previous_year_rating
## no_of_trainings           1.00000000 -0.081542733         -0.063126473
## age                      -0.08154273  1.000000000          0.006008234
## previous_year_rating     -0.06312647  0.006008234          1.000000000
## length_of_service        -0.05422064  0.624249658          0.000252746
## avg_training_score        0.04443301 -0.056744271          0.075139112
##                      length_of_service avg_training_score
## no_of_trainings           -0.054220641         0.04443301
## age                        0.624249658        -0.05674427
## previous_year_rating       0.000252746         0.07513911
## length_of_service          1.000000000        -0.04226047
## avg_training_score        -0.042260471         1.00000000
\end{verbatim}

Una correlacion de 4.6\% entre los dos variables no\_of\_trainings y
avg\_training\_score.

Una correlacion de 62\% entre los dos variables age y
length\_of\_service, ademas de una correlacion baja de 0.57\% entre los
variables age y previous\_year\_rating.

Una correlacion de 7,5\% entre los dos variables previous\_year\_rating
y avg\_training\_score, ademas una correlacion baja de 0.12\% entre la
variable previous\_year\_rating y la variable length\_of\_service.

La variable numerica employee\_start\_age no esta incluida porque es
resultado de una substitucion de dos variables numericos que existen en
la Matrix que son age y length\_of\_service, para evitar la redundancia.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{pca}{%
\section{PCA}\label{pca}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Realizar la técnica PCA con las variables de la Matrix

\begin{verbatim}
## Call:
## princomp(x = epc)
## 
## Standard deviations:
##       Comp.1       Comp.2       Comp.3       Comp.4       Comp.5 
## 6.774037e-01 4.749212e-01 3.994590e-01 1.679520e-01 8.359574e-09 
## 
##  5  variables and  5 observations.
\end{verbatim}

Contribucion de cada variable a cada componente

\begin{verbatim}
##    Comp.1    Comp.2    Comp.3    Comp.4    Comp.5 
## 0.5261123 0.7847110 0.9676590 1.0000000 1.0000000
\end{verbatim}

El componente 1 contiene el 52\% de la variabilidad.

El componente 1 más el componente 2 acumulan el 78\% de la variabilidad.

El componente 1 más el componente 2 más el componente 3 acumulan el 96\%
de la variabilidad, y así succesivamente.

Vemos que solamente con los tres primeros componentes podemos explicar
el 96,77\% de la variabilidad de la dataset, de manera que el estudio de
nuestra dataset principal sobre estos tres componentes será suficiente
para entender aplicar una predicion rezonables.\\

\end{document}
